/**
 * Counter-proposal letter viewer.
 * BUG-23 FIX: Replaced <pre> with ReactMarkdown so Claude's formatted letter
 * renders properly (bold, headings, bullets) instead of showing raw asterisks.
 */
import { useRef, useState } from 'react'
import { motion } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import toast from 'react-hot-toast'

interface Props {
  letter: string
  jurisdiction: string
}

export default function CounterProposalViewer({ letter, jurisdiction }: Props) {
  const letterRef = useRef<HTMLDivElement>(null)
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(letter)
    setCopied(true)
    toast.success('Letter copied to clipboard!')
    setTimeout(() => setCopied(false), 3000)
  }

  const handleDownload = () => {
    const blob = new Blob([letter], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `LeaseLens-Counter-Proposal-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Letter downloaded!')
  }

  const handleEmail = () => {
    const subject = encodeURIComponent('Rental Agreement — Counter-Proposal (LeaseLens)')
    const body = encodeURIComponent(letter)
    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  return (
    <div className="space-y-4">
      {/* Action bar */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div>
          <h3 className="font-display text-lg font-semibold text-slate-900">
            Counter-Proposal Letter
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            AI-generated · Cites specific laws · Review before sending
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleEmail}
            className="text-xs font-medium px-3 py-2 border border-slate-200 rounded-lg
                       hover:bg-slate-50 transition-colors text-slate-600"
          >
            ✉️ Email
          </button>
          <button
            onClick={handleDownload}
            className="text-xs font-medium px-3 py-2 border border-slate-200 rounded-lg
                       hover:bg-slate-50 transition-colors text-slate-600"
          >
            ⬇️ Download
          </button>
          <motion.button
            onClick={handleCopy}
            whileTap={{ scale: 0.95 }}
            className={`text-xs font-semibold px-3 py-2 rounded-lg transition-all ${
              copied
                ? 'bg-green-500 text-white'
                : 'bg-navy-500 text-white hover:bg-navy-600'
            }`}
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </motion.button>
        </div>
      </div>

      {/* BUG-23 FIX: ReactMarkdown renders bold/headings/bullets properly */}
      <div
        ref={letterRef}
        className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden"
      >
        <div className="h-1.5 bg-gradient-to-r from-navy-700 via-blue-500 to-navy-700" />
        <div className="p-6 max-h-[520px] overflow-y-auto">
          <div className="prose prose-sm prose-slate max-w-none
                          prose-headings:font-display prose-headings:text-slate-900
                          prose-strong:text-slate-900 prose-p:text-slate-700
                          prose-li:text-slate-700 prose-p:leading-relaxed">
            <ReactMarkdown>{letter}</ReactMarkdown>
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="flex items-start gap-2 p-3 bg-amber-50 border border-amber-200 rounded-lg">
        <span className="text-sm flex-shrink-0">⚖️</span>
        <p className="text-[11px] text-amber-800 leading-relaxed">
          This letter was generated by LeaseLens AI with{' '}
          <strong>{jurisdiction}</strong>-specific legal context. Review carefully before
          sending. <strong>This is not legal advice.</strong> For CRITICAL findings,
          consult an advocate registered with the Bar Council of India.
        </p>
      </div>
    </div>
  )
}
